### ISSUE TITLE
send "enter" key

### ISSUE THREAD

**Issue by szczepanR** [gaozhao1989/pyjab#14]
Hi Gary,
do you plan to add a function for hitting the "enter" key?
It would be useful for submitting some values in forms.
I did something like below and it works but maybe you will add some extra code:
```
    def send_key(self, value: str) -> None:
        value = str(value)
        self.win32_utils._press_key(value)
```

**Comment by gaozhao1989** [comment]
Hi @szczepanR,
Thanks for your feedback.
As your said, the pyjab(win32api) already support send keys like: "enter", "shift", "ctrl"...
you can directly use it with func "win32_utils._press_key"
please reference with vk list in file "win32utils"

**Comment by szczepanR** [comment]
thanks, closing the issue
