### ISSUE TITLE
I don't understand the Win32 API part.

### ISSUE THREAD

**Issue by xinchenll** [gaozhao1989/pyjab#17]
My English is not good. First of all, I think this is a very good module.I hope you can keep doing it.

I have read your document carefully, and feel that it is too simple, there should be many functions that have not been written out.

I don't understand the Win32 API part.

your document:
Win32utils()._send_keys("abc")

Where did Win32utils() import from?
I don't understand that .I hope you can provide a complete example with JabDriver.

This is very important to me. Thank you again!

**Comment by gaozhao1989** [comment]
Hi @xinchenll,
Please reference with document
> pyjab also integrate screenshot utils which provide by Pillow, window, mouse and keyboard action by pywin32.

Back to your question, win32 api is referenced from library [pywin32](https://github.com/mhammond/pywin32)
From win32 api you can directly use keyboard and mouse event.

Samples:
```
some_element = jabdriver.find_element(xxx, xxx)

# click action(use mouse event)
some_element.click(simulate=True)
# keyboard action(use keyboard event)
some_element.send_text("ABC", simulate=True)
```

Also, you can directly leave messages in Chinese.
Hope this will help you.

**Comment by xinchenll** [comment]
非常感谢大佬的回复，还有个问题就是使用类似 find_element_by_xpath这样的方法中 ，xpath参数设计规则和方法是不是和selenium 一样的呢？

其实我一直在寻找一款PC端自动化测试的模块，感觉非常难找，用得最多的可能就是pywinauto，但是它不能用在java的应用上，而且已经不更新了，最后还是通过google搜索和google翻译才找到你这款模块包，所以很希望你能坚持把它做好。

**Comment by xinchenll** [comment]
问题解决了
