### ISSUE TITLE
About BOOL GetAccessibleContextAt(long vmID, AccessibleContext acParent, jint x, jint y, AccessibleContext *ac)

### ISSUE THREAD

**Issue by sunnic1988** [gaozhao1989/pyjab#2]
About BOOL GetAccessibleContextAt(long vmID, AccessibleContext acParent, jint x, jint y, AccessibleContext *ac)
This API can not work for every Java window. It is work in the demo(SwingSet2),  it can be return corrent AccessibleContext.
but it can not work in Java Window Oracle EBS ERP, it return the top compoent  AccessibleContext. Do you have any idea about it?

I have try to add these code into jabelement.py
`    def get_accessible_context_at(self, x, y) -> JABElement:
        target_accessible_context = self._get_accessible_context_at(x, y, None, None, None)
        return JABElement(self.bridge, self.hwnd, self.vmid, target_accessible_context)`

`    def _get_accessible_context_at(
        self,
        x: c_int,
        y: c_int,
        vmid: c_long = None,
        parent_acc: JOBJECT64 = None,
        new_acc: JOBJECT64 = JOBJECT64(),
    ) -> JOBJECT64:
        """
        Retrieves an AccessibleContext object of the window or object that is under the mouse pointer.
        BOOL GetAccessibleContextAt(long vmID, AccessibleContext acParent, jint x, jint y, AccessibleContext *ac)
        Args:
            x: position x of child accessible context
            y: position y of child accessible context
            vmid: java vmid of specific java window
            parent_acc: parent accessible context of specifc java object
            new_acc: new accessible context of specifc java object
        Returns:
            AccessibleContext: get Accessible Context success
            None: get Accessible Context failed
        """
        vmid = self.vmid
        parent_acc = self.accessible_context
        new_acc = new_acc if isinstance(new_acc, JOBJECT64) else JOBJECT64()
        result_acc = self.bridge.getAccessibleContextAt(vmid, parent_acc, x, y, new_acc)
        if not result_acc or not new_acc:
            raise JABException(self.int_func_err_msg.format("GetAccessibleContextAt"))
        if not bool(self.bridge.isSameObject(self.vmid, parent_acc, new_acc)):
            return new_acc
        # elif new_acc != parent_acc:
        #     self.release_jabelement(new_acc)
        return None`

**Comment by gaozhao1989** [comment]
Hi

Actually, I not still get correct callback from this function.
Back to your question.
Would you please try find element with below function? Like: by_name, by_role, by_states, by_object_depth, by_children_count, by_index_in_parent or  by_xpath
These functions will enum all matched children AccessibleContext from root/specific AccessibleContext.
You can find "matched jab element" first, then verify position "x", "y" in element information.

**Comment by gaozhao1989** [comment]
Close since can not handle JAB issue
