### ISSUE TITLE
any hope to click on element with bounds {X=-1,Y=-1, Width=-1,Height=-1} ?

### ISSUE THREAD

**Issue by szczepanR** [gaozhao1989/pyjab#20]
Hi, I have a table where all cells are elements type Panel.  Unfortunately all of the cells have bounds {X=-1,Y=-1, Width=-1,Height=-1}. That shows "Access Bridge Explorer". I checked that NVDA also did not recognize cells in this table.
I checked that SilkTest is able to somehow get cells. 
I know that probably silktest has their own magic but maybe you have idea
thanks in advance

**Comment by gaozhao1989** [comment]
Hi @szczepanR,
Start from pyjab v1.0.7, the internal function support get cell elements from table.
You can directly use it by func "get_cell".

I don't known what you expected next action on table cell.
But it does support get text, set text and click function, you can try and set parameter "simulate" as True

**Comment by szczepanR** [comment]
get_cell() works for geting specified cell but sill bounds for given cell are {X=-1,Y=-1, Width=-1,Height=-1} and I can't click on it even with "simulate" as true

**Comment by gaozhao1989** [comment]
After checked with JAB API, only accessible selection support for role table.
That mean user need to interact with table element need follow below steps:
1. add row or column(actually need cell) to accessible selection.
2. use keyboard event or mouse event handle user action on selection item.

Will check if that is correct or not
![Screenshot 2021-12-02 125255](https://user-images.githubusercontent.com/17725280/144360041-92486b15-f63f-4231-8da0-7f82a42b74d5.png)

**Comment by szczepanR** [comment]
thanks,
can you check in "access bridge explorer" that you have option group "visible children" for the table?
I have that group, and every cell has bounds but without name

**Comment by gaozhao1989** [comment]
> thanks, can you check in "access bridge explorer" that you have option group "visible children" for the table? I have that group, and every cell has bounds but without name

Hi @szczepanR,
That a good idea. I have retry with your mentioned, it works for get the correct information from table.
Here is the sample:
```
jabdriver = JABDriver("TableFTFEditDemo")
table = jabdriver.find_element_by_role("table")
info = VisibleChildenInfo()
result = table.bridge.getVisibleChildren(table.vmid, table.accessible_context, 0, byref(info))
element = JABElement(table.bridge, table.hwnd, table.vmid, info.children[2])
print(element.get_element_information())
```
Output as below get the correct bounds:
```
{
    'name': 'Snowboarding',
    'description': '',
    'role': 'label',
    'role_en_us': 'label',
    'states': ['enabled', 'focusable', 'visible', 'opaque', 'showing', 'transient'],
    'states_en_us': ['enabled', 'focusable', 'visible', 'opaque', 'showing', 'transient'],
    'bounds': {'x': 512, 'y': 534, 'height': 15, 'width': 99},
    'object_depth': 7,
    'index_in_parent': 2,
    'children_count': 0,
    'accessible_component': True,
    'accessible_action': False,
    'accessible_selection': False,
    'accessible_text': False,
    'text': None,
    'table': None
}
```
Unfortunately, these cells in table does not support any accessible actions, so will investigate if there is any other way to handle the user action on these cells

**Comment by szczepanR** [comment]
Many thanks, we can simulate click on the specified cell. Can I test above code with latest pyjab release?

**Comment by szczepanR** [comment]
Btw. Your code can be helpful to solve my other issue with check if element which I want click is visible or not.

**Comment by gaozhao1989** [comment]
Hi @szczepanR,
Changes already pushed to branch dev, it will be a great help for me if you can test against with latest change for visible children. Thanks!

**Comment by szczepanR** [comment]
Hi, 
so far i tested the part with sample code 
`
jabdriver = JABDriver("TableFTFEditDemo")
table = jabdriver.find_element_by_role("table")
info = VisibleChildenInfo()
result = table.bridge.getVisibleChildren(table.vmid, table.accessible_context, 0, byref(info))
element = JABElement(table.bridge, table.hwnd, table.vmid, info.children[2])
print(element.get_element_information())
`
I also get correct information in my application and I can simulate click on the element
I need to get total number of the visible children, to look for specific index_in_parent value, soI tred to use `JABElement(table.bridge, table.hwnd, table.vmid, info.returnedChildrenCount)`, but my application under tests crashes.

**Comment by gaozhao1989** [comment]
> Hi, 
> 
> so far i tested the part with sample code 
> 
> 
> 
> ```
> 
> jabdriver = JABDriver("TableFTFEditDemo")
> 
> 
> 
> table = jabdriver.find_element_by_role("table")
> 
> 
> 
> info = VisibleChildenInfo()
> 
> 
> 
> result = table.bridge.getVisibleChildren(table.vmid, table.accessible_context, 0, byref(info))
> 
> 
> 
> element = JABElement(table.bridge, table.hwnd, table.vmid, info.children[2])
> 
> 
> 
> print(element.get_element_information())
> 
> ```
> 
> 
> 
> I also get correct information in my application and I can simulate clicking on the element
> 
> I need to get a total number of the visible children, to look for specific index_in_parent value, soI tried to use `JABElement(table.bridge, table.hwnd, table.vmid, info.returnedChildrenCount)`, but my application under tests crashes.
> 
> 

Hi @szczepanR,

VisibleChildrenInfo attribute returnedChildrenCount will get the viable children count. You can also use get elements.

BTW, you need pass the accessibleContext as the last parameter.

**Comment by szczepanR** [comment]
Hi,
I found
`visible_children_count = table.bridge.getVisibleChildrenCount(table.vmid, table.accessible_context, 0, byref(info))` 
and now I have working solution for my needs regarding clicking table cells. Many thanks
it there possibility to to have functions "visible_chldren_count" and "visible_children" available for jabElement like other functions (i.e. "find_element_by_name")

**Comment by gaozhao1989** [comment]
Hi,
check the visible children count with below sample
```
len(driver.find_elements_by_xxx("xxx", visible=True))
```

**Comment by szczepanR** [comment]
I tried `vis_child_count = len(jabdriver.find_element_by_role("label", visible=True))`
as aresult I got
`pyjab.common.exceptions.JABException: ("jab element not found by 'role' with locator 'label'", None)`

**Comment by gaozhao1989** [comment]
works find in my side, but seems does not get the correct value.
let me add func get visible children count later.
![image](https://user-images.githubusercontent.com/17725280/145326011-10607fab-5886-4585-bf0f-60704c0bf44f.png)

**Comment by szczepanR** [comment]
This is not urgent, I have working and stable solution for this issue. 
Many thanks for solving the biggest issue (so far) in testing my application.
Looking forward for the new release.

**Comment by szczepanR** [comment]
should I close this issue?

**Comment by gaozhao1989** [comment]
Close in PR #25
