### ISSUE TITLE
table的点击事件的问题，困扰我多日了

### ISSUE THREAD

**Issue by xinchenll** [gaozhao1989/pyjab#22]
应用界面截图：
![image](https://user-images.githubusercontent.com/86393373/144191688-7ab96a3b-b477-4846-b63a-cd4860f1e173.png)
看得出这是个table, 于是我用下面的语句测试：
ele = driver1.find_element_by_xpath("//viewport[@objectdepth=10 @indexinparent=0]/table")
print(ele)
aa=ele.get_cell(0,2)
print(aa.get_element_information())
aa.click()

控制台输出为：
<pyjab.jabelement.JABElement object at 0x0000000002C235E0>
<pyjab.accessibleinfo.AccessibleTableCellInfo object at 0x0000000002C245C0>
1
{'name': '李一龙', 'description': '', 'role': 'label', 'role_en_us': 'label', 'states': ['启用', '可集中', '可见', '不透明'], 'states_en_us': ['enabled', 'focusable', 'visible', 'opaque'], 'bounds': {'x': -1, 'y': -1, 'height': -1, 'width': -1}, 'object_depth': 0, 'index_in_parent': -1, 'children_count': 0, 'accessible_component': True, 'accessible_action': False, 'accessible_selection': False, 'accessible_text': False, 'text': None, 'table': None}
Traceback (most recent call last):
  File "D:/python/appPageObject/pyjab2.py", line 34, in <module>
    aa.click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyjab\jabelement.py", line 365, in click
    self._do_accessible_action(action="click")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyjab\jabelement.py", line 315, in _do_accessible_action
    raise JABException("JABElement does not support Accessible Action")
pyjab.common.exceptions.JABException: ('JABElement does not support Accessible Action', None)

从上面的信息可以看出，返回的是 'role': 'label' 的控件，但是为什么这个控件不支持 jab的点击事件呢？可不可以优化下，因为如果用模拟点击的话，注意它的 bounds: {'x': -1, 'y': -1, 'height': -1, 'width': -1} , 可以看出，模拟点击也是不行的，所以能不能给我解决这个问题，就算是专门为这个label单独写个click方法也行，比如click_in_label()之类的。

**Comment by xinchenll** [comment]
另外jab不支持这个鼠标点击会不会我电脑的java版本低的问题呢？我电脑java_home是jre1.8.0_172 64位,  被控制的java应用是jre1.8.0_202 32位启动的（因为应用的局限性只能用32位），我不知道这个问题会产生什么样的影响？

**Comment by gaozhao1989** [comment]
> 另外jab不支持这个鼠标点击会不会我电脑的java版本低的问题呢？我电脑java_home是jre1.8.0_172 64位, 被控制的java应用是jre1.8.0_202 32位启动的（因为应用的局限性只能用32位），我不知道这个问题会产生什么样的影响？

可以使用模拟点击两次来“模拟”鼠标的双击动作行为

**Comment by gaozhao1989** [comment]
Duplicate of #20 
mark as duplicate due to same issue

**Comment by gaozhao1989** [comment]
Hi @xinchenll,
此问题已在 #20 上更新内容，但目前 pyjab 仍无法处理此问题的反馈内容。
未来将会尝试假设方案是否能够解决该问题。

**Comment by gaozhao1989** [comment]
请参考 #20  的尝试解决方案，可以获取到表格内信息，但目前用户操作行为事件仍然需要进一步研究
