### ISSUE TITLE
请问如何对元素进行鼠标右键的点击事件？

### ISSUE THREAD

**Issue by xinchenll** [gaozhao1989/pyjab#23]
如题。。。。

**Comment by gaozhao1989** [comment]
请参考 win32api
```
def _click_mouse(self, x: int, y: int, hold: int = 0) -> None:
        win32api.SetCursorPos((x, y))
        win32api.mouse_event(win32con.MOUSEEVENTF_RIGHTDOWN, x, y, 0, 0)
        if hold:
            time.sleep(hold)
        win32api.mouse_event(win32con.MOUSEEVENTF_RIGHTUP, x, y, 0, 0)
```

**Comment by xinchenll** [comment]
非常感谢，很期待你的新版本到早些到来

**Comment by gaozhao1989** [comment]
Close in PR #25

**Comment by szczepanR** [comment]
Hi Gary,
how to use right-click in the newest release?

**Comment by gaozhao1989** [comment]
> Hi Gary, how to use right-click in the newest release?

Hi, please use win32utils func "_click_mouse" with parameter button="right".
I'm not consider merge this within JAB click function since right click does not have internal JAB support.
So, please pass the position x and y to this function to handle your scenario. Thanks!
