### ISSUE TITLE
wildcard for JABDriver argument

### ISSUE THREAD

**Issue by szczepanR** [gaozhao1989/pyjab#24]
Hi Gary,
is there possibility to look for a window title with wildcard i.e. JABDriver(*title*) as a parameter?

**Comment by gaozhao1989** [comment]
It's not possible to handle wildcard in current pyjab.

But you can try modify the logic in func "get_hwnd_by_title" of file "win32utils" in your side. It's possible to use wildcard get the Java application title.

**Comment by szczepanR** [comment]
thanks, will try get_hwnd_by_title function
