### ISSUE TITLE
Function for checking of the element existence

### ISSUE THREAD

**Issue by szczepanR** [gaozhao1989/pyjab#26]
Hi,
Can you help me with my issue? I want to check if there are no (in most cases unexpected) elements visible during the test execution?
i.e. exists_element_by_name will return true or false rather than the exception

**Comment by gaozhao1989** [comment]
Please use find element within "try ... except ... " segment.

**Comment by szczepanR** [comment]
Happy New Year Gary,
it works, thanks.
