### ISSUE TITLE
是否考虑以LGPL协议分发

### ISSUE THREAD

**Issue by tshemeng** [gaozhao1989/pyjab#30]
pyjab更多以类库的方式被使用，似乎LGPL协议比GPL协议更为适用。

虽然审视pyjab所采用的开源协议是使用者的义务，但当前的使用者可能没有意识到自己的项目也必须以GPL协议“公开”。

**Comment by gaozhao1989** [comment]
你好
pyjab 只能以 GPLv2 协议进行分发，感谢关注

关于 GPLv2 的协议内容，您可能有些误解，详细请参考：[URL](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)

**Comment by tshemeng** [comment]
感谢回复

改为 LGPL 只是一个提议，既然您明确以 GPLv2 发布 pyjab，稍后我会关闭这个 issue

此外，我看了 GPLv2 协议，以及 GNU 对于 GPLv2 的解释，即便开发者在自己的程序代码中用到了 GPL 的库，自己的程序代码也需要以 GPL 发布，参考解释： [GPL 2.0 FAQ Library Is GPL](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#IfLibraryIsGPL)，您说我对 GPLv2 有误解，我不清楚我哪里理解的不对，还请赐教

**Comment by gaozhao1989** [comment]
Close without comment
