### ISSUE TITLE
missing "desktop pane" role

### ISSUE THREAD

**Issue by szczepanR** [gaozhao1989/pyjab#46]
Hi, I tried the following function:
 `desktop_pane = jabdrv.find_element_by_xpath("//desktop pane[@objectdepth=7]")`

and I am getting this error:
`("incorrect role set 'desktop pane'", None)`

So I added to role.py this:
`DESKTOP_PANE = "desktop pane"`

After that I am getting:
`'JABElement' object is not subscriptable`

Could you tell me what is wrong?

**Comment by gaozhao1989** [comment]
Hi @szczepanR,
Thanks for your feedback, this issue can be reproduced from find by xpath.
And will be fixed in next release.

But the question in my side, this can be fixed by add role in role.py as your description.
would you please give more information about your scenarios? thanks!

**Comment by szczepanR** [comment]
I checked again, and you are right it works after adding the role "desktop pane" to role.py.
Need to remember, always double-check  :)
Thanks.
