### ISSUE TITLE
大佬请问下能否把某些内部方法改成外部可调用的呢

### ISSUE THREAD

**Issue by zhanbinyy** [gaozhao1989/pyjab#47]
比如：_generate_childs_from_element/_get_accessible_selection_from_context 等，我们这边有场景需要直接调用这些内部方法

**Comment by gaozhao1989** [comment]
Hi @zhanbinyy,

事实上你可以直接在实例化 JABElement 之后调用这些函数，两个函数都没有限定只能使用当前类的属性。
例如在函数__generate_childs_from_element_ 中
```
jabelement = jabelement or JABElement(
            self.bridge, self.hwnd, self.vmid, self.accessible_context
        )
```
直接调用该函数即可

**Comment by gaozhao1989** [comment]
Close since not an issue
