### ISSUE TITLE
有什么好的方法可以定位元素吗

### ISSUE THREAD

**Issue by cluic** [gaozhao1989/pyjab#48]
大佬你好：
1.我现在用javamonkey可以查看窗口树结构，但是定位不太方便，有没有类似可以拾取元素的工具
2.目前遇到个问题，窗口内有个动态元素，窗口激活才显示，不激活就消失了，不知道怎么定位到这个元素

**Comment by gaozhao1989** [comment]
Hi @cluic,

你可以使用 [Access Bridge Explorer](https://github.com/google/access-bridge-explorer)

**Comment by cluic** [comment]
谢谢提供这么好用的工具，非常感谢~
