### ISSUE TITLE
请问如何连接至Applet呢？

### ISSUE THREAD

**Issue by yetshenwet** [gaozhao1989/pyjab#49]
一个由网站弹出的新窗口，例如OracleERP，通过title或handle初始化JABDriver会出现找不到相应的Java window和handle不是一个Java window的异常。这种情况下我应该如何初始化呢？
普通的Java应用程序例如intelliJ IDEA的连接是没有问题的

**Comment by gaozhao1989** [comment]
Hi，

我尝试使用了 title 和 hwnd 分别实例化 JABDriver，并没有发现您提到的问题。

由于我本地并没有 Oracle ERP demo，很遗憾并不能复现您提到的场景。

但根据您反馈的信息来看，很有可能目标的窗口并不是一个 Java 应用程序，您可以尝试使用 Inspector 查看或者 jab api 确认，并尝试提供更多信息。

**Comment by yetshenwet** [comment]
感谢回复，我最开始的问题描述不是非常清晰，目标窗口确实不是一个Java应用程序，而是一个浏览器窗口，内部是Java Applet。

上述的浏览器窗口是这样生成的：
点击网页1中的一个按钮，网页2打开，当网页2加载完成时，一个内部是Java Applet的浏览器窗口打开

网页2的部分DOM类似于：
```html
<object>
    <param name="legacy_lifecycle" value="false" valueType="" />
    <param name="type" value="application/x-java-applet" valueType="" />
    <!-- MANY PARAM TAG FOLLOWED -->
</object>
```
其中并没有与生成的Java Applet的UI相关的结构

**Comment by yetshenwet** [comment]
> 

感谢回复，我最开始的问题描述不是非常清晰，目标窗口确实不是一个Java应用程序，而是一个浏览器窗口，内部是Java Applet。

上述的浏览器窗口是这样生成的：
点击网页1中的一个按钮，网页2打开，当网页2加载完成时，一个内部是Java Applet的浏览器窗口打开

网页2的部分DOM类似于：
```html
<object>
    <param name="legacy_lifecycle" value="false" valueType="" />
    <param name="type" value="application/x-java-applet" valueType="" />
    <!-- MANY PARAM TAG FOLLOWED -->
</object>
```
其中并没有与生成的Java Applet的UI相关的结构

**Comment by gaozhao1989** [comment]
Hi,

您需要尝试从网页中分离 Java Applet，方可以使用 pyjab

**Comment by gaozhao1989** [comment]
Close due to not an issue from pyajb
