### ISSUE TITLE
无法找到特定的元素

### ISSUE THREAD

**Issue by 531142747** [gaozhao1989/pyjab#50]
问题：软件为nc65程序 进入到某个页面 里面所有元素都无法获取到。用第三方rpa软件可以获取到，附上截图
图片为需要捕获的元素

![image](https://user-images.githubusercontent.com/33396418/167365482-1b98385a-ad1d-4fa9-9da9-8cdb3e3f6d4e.png)
![image](https://user-images.githubusercontent.com/33396418/167365417-4e146fb4-ce5a-4906-8779-2feddc356f0b.png)

**Comment by 531142747** [comment]
谢谢老大回复。这个是付费应用没办法提供到场景复现，目前只能通过前台去实现自动化。

**Comment by gaozhao1989** [comment]
你好，
如果能有提供的信息可以在此 issue 上进行回复。暂时无法进行复现就此关闭此 issue
