### ISSUE TITLE
win32com.client.Dispatch("WScript.Shell").SendKeys(' ')

### ISSUE THREAD

**Issue by discovery-131794** [gaozhao1989/pyjab#53]
I don't understand why we need this line of code in function "_set_window_foreground"

**Comment by gaozhao1989** [comment]
Hi @discovery-131794,

Thanks for your response.
This sentence this used for recover window from background for some strange scenarios(Still not get reason why not working) which cannot directly recover by func "SetForegroundWindow".
Please advice if you have better solution. 
Many thanks!

**Comment by gaozhao1989** [comment]
Hi @discovery-131794,

Thanks for your information.
 I'm still looking for better solution on this, do you have any other idea?

**Comment by discovery-131794** [comment]
Hi @gaozhao1989 ,
win32 API "SwitchToThisWindow" have the same effect to take window to foreground even if the window is minimized.
But it seems this function is not meant to be general use.
[https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-switchtothiswindow](url)
