### ISSUE TITLE
ERROR: Cannot install pyjab==1.0.0, pyjab==1.0.1, pyjab==1.0.3, pyjab==1.0.4, pyjab==1.0.5, pyjab==1.0.6, pyjab==1.0.7, pyjab==1.0.8, pyjab==1.0.9, pyjab==1.1.0, pyjab==1.1.1, pyjab==1.1.2, pyjab==1.1.3, pyjab==1.1.4, pyjab==1.1.5, pyjab==1.1.6 and pyjab==1.1.7 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by anthony-nyc** [gaozhao1989/pyjab#64]
Hi,

Although the instruction is provided as below, I am not sure how to get this resolved because it says v1.0.0 thru 1.1.7 which means all of released version.

Do you have any ideas on this?

FYI,  below is the version of python and pip. It looks all up to date.
Also, I tried to install pyjab in the mac but I got the same error too.

Regards,
Anthony

C:\Users\antho\projects>python --version  
Python 3.10.6

C:\Users\antho\projects>pip --version
pip 22.3 from C:\msys64\mingw64\lib\python3.10\site-packages\pip (python 3.10)

C:\Users\antho\projects>

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

C:\Users\antho\projects>**pip install pyjab**            
Collecting pyjab
  Using cached pyjab-1.1.7-py2.py3-none-any.whl (40 kB)
Collecting Pillow>=8.3.2
  Using cached Pillow-9.3.0.tar.gz (50.4 MB)
  Preparing metadata (setup.py) ... done
Collecting pyjab
  Using cached pyjab-1.1.6-py2.py3-none-any.whl (40 kB)
  Using cached pyjab-1.1.5-py2.py3-none-any.whl (40 kB)
  Using cached pyjab-1.1.4-py2.py3-none-any.whl (39 kB)
  Using cached pyjab-1.1.3-py2.py3-none-any.whl (39 kB)
  Using cached pyjab-1.1.2-py2.py3-none-any.whl (39 kB)
  Using cached pyjab-1.1.1-py2.py3-none-any.whl (39 kB)
  Using cached pyjab-1.1.0-py2.py3-none-any.whl (37 kB)
Collecting pypiwin32==223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting Pillow==8.3.2
  Using cached Pillow-8.3.2.tar.gz (48.8 MB)
  Preparing metadata (setup.py) ... done
Collecting pyjab
  Using cached pyjab-1.0.9-py2.py3-none-any.whl (37 kB)
  Using cached pyjab-1.0.8-py2.py3-none-any.whl (37 kB)
  Using cached pyjab-1.0.7-py2.py3-none-any.whl (37 kB)
  Using cached pyjab-1.0.6-py2.py3-none-any.whl (33 kB)
Collecting Pillow==8.2.0
  Using cached Pillow-8.2.0.tar.gz (47.9 MB)
  Preparing metadata (setup.py) ... done
Collecting pyjab
  Using cached pyjab-1.0.5-py2.py3-none-any.whl (33 kB)
  Using cached pyjab-1.0.4-py2.py3-none-any.whl (33 kB)
  Using cached pyjab-1.0.3-py2.py3-none-any.whl (33 kB)
  Using cached pyjab-1.0.1-py2.py3-none-any.whl (34 kB)
  Using cached pyjab-1.0.0-py2.py3-none-any.whl (34 kB)
**ERROR: Cannot install pyjab==1.0.0, pyjab==1.0.1, pyjab==1.0.3, pyjab==1.0.4, pyjab==1.0.5, pyjab==1.0.6, pyjab==1.0.7, pyjab==1.0.8, pyjab==1.0.9, pyjab==1.1.0, pyjab==1.1.1, pyjab==1.1.2, pyjab==1.1.3, pyjab==1.1.4, pyjab==1.1.5, pyjab==1.1.6 and pyjab==1.1.7 because these package versions have conflicting dependencies.**

The conflict is caused by:
    pyjab 1.1.7 depends on pywin32>=302
    pyjab 1.1.6 depends on pywin32>=302
    pyjab 1.1.5 depends on pywin32>=302
    pyjab 1.1.4 depends on pywin32>=302
    pyjab 1.1.3 depends on pywin32>=302
    pyjab 1.1.2 depends on pywin32>=302
    pyjab 1.1.1 depends on pywin32>=302
    pyjab 1.1.0 depends on pywin32==302
    pyjab 1.0.9 depends on pywin32==302
    pyjab 1.0.8 depends on pywin32==302
    pyjab 1.0.7 depends on pywin32==301
    pyjab 1.0.6 depends on pywin32==300
    pyjab 1.0.5 depends on pywin32==300
    pyjab 1.0.4 depends on pywin32==300
    pyjab 1.0.3 depends on pywin32==300
    pyjab 1.0.1 depends on pywin32==300
    pyjab 1.0.0 depends on pywin32==300

**To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts**

**Comment by gaozhao1989** [comment]
Hi @anthony-nyc,

Please check the pywin32 version within your local environment.

**Comment by anthony-nyc** [comment]
Hi Gary,

Thanks for the quick response.
Yes, I’ve just installed pywin32 and then installed pyjab successfully.

However, the sample code in pyjab/README_CN.rst in GitHub.com doesn’t work as expected.
For example, the sample code is showing as below:

login_btn = jabdriver.find_element_by_name("btnOk")  // replaced Ok with btnOk in my java sample.

and returns an error as below.

When you have some time, would it be possible to update README_CN.rst with some more examples like retrieve a value from JTextBox and assign a value into JTextbox?
That would be greatly appreciated!

Anthony

[Running] python -u "c:\Users\antho\projects\python\HelloWord.py"
2022-11-05 22:04:02,537 INFO pyjab init jab
2022-11-05 22:04:02,570 INFO pyjab init jab success
Traceback (most recent call last):
  File "c:\Users\antho\projects\python\HelloWord.py", line 4, in <module>
    jabdriver.find_element_by_name("btnOk")
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 296, in find_element_by_name
    return self.root_element.find_element_by_name(value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 965, in find_element_by_name
    return self.find_element(by=By.NAME, value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 1328, in find_element
    raise JABException(
pyjab.common.exceptions.JABException: ("jab element not found by 'name' with locator 'btnOk'", None)

[Done] exited with code=1 in 0.536 seconds

**Comment by anthony-nyc** [comment]
I tried find_element_by_index_in_parent(1) since I could find the index_in_parent using Access Bridge Explorer.
But I think it was lucky because I didn’t specify Object Depth below but it worked.

from pyjab.jabdriver import JABDriver
jabdriver = JABDriver("Welcome!")
txt = jabdriver.find_element_by_index_in_parent(1)
txt.send_text("Done!")

I have a combo box, whose Object Depth is 9 and not sure how to access one of items in the combo box.

Do you have any tutorials showing how to access each UI elements?
That would be greatly appreciated. It would be so hard to figure out ways to access each type of UI elements.

Thank you so much!

Anthony


From: Anthony ***@***.***>
Sent: Saturday, November 5, 2022 10:07 PM
To: ***@***.***>
Subject: RE: [gaozhao1989/pyjab] ERROR: Cannot install pyjab==1.0.0, pyjab==1.0.1, pyjab==1.0.3, pyjab==1.0.4, pyjab==1.0.5, pyjab==1.0.6, pyjab==1.0.7, pyjab==1.0.8, pyjab==1.0.9, pyjab==1.1.0, pyjab==1.1.1, pyjab==1.1.2, pyjab==1.1.3, pyjab==1.1.4, pyjab==1.1...

Hi Gary,

Thanks for the quick response.
Yes, I’ve just installed pywin32 and then installed pyjab successfully.

However, the sample code in pyjab/README_CN.rst in GitHub.com doesn’t work as expected.
For example, the sample code is showing as below:

login_btn = jabdriver.find_element_by_name("btnOk")  // replaced Ok with btnOk in my java sample.

and returns an error as below.

When you have some time, would it be possible to update README_CN.rst with some more examples like retrieve a value from JTextBox and assign a value into JTextbox?
That would be greatly appreciated!

Anthony

[Running] python -u "c:\Users\antho\projects\python\HelloWord.py"
2022-11-05 22:04:02,537 INFO pyjab init jab
2022-11-05 22:04:02,570 INFO pyjab init jab success
Traceback (most recent call last):
  File "c:\Users\antho\projects\python\HelloWord.py", line 4, in <module>
    jabdriver.find_element_by_name("btnOk")
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 296, in find_element_by_name
    return self.root_element.find_element_by_name(value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 965, in find_element_by_name
    return self.find_element(by=By.NAME, value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 1328, in find_element
    raise JABException(
pyjab.common.exceptions.JABException: ("jab element not found by 'name' with locator 'btnOk'", None)

[Done] exited with code=1 in 0.536 seconds

**Comment by gaozhao1989** [comment]
Hi @anthony-nyc,

Please reference with from this document and thanks!
https://github.com/gaozhao1989/pyjab/wiki/3-pyjab

**Comment by anthony-nyc** [comment]
Hi Gary,

Thanks for your response.
While I was trying to figure out why pyjab is not able to access UI element using Name, I noticed that Access Bridge Explorer shows blank in Name field.

Could you please let me know how we can identify the name of UI elements?
I thought that we have to use Access Bridge Explorer but it shows blank in a field of Name.

For example, here<https://github.com/supanadit/restsuite/releases> is a sample Java GUI application and I wrote one line code below to access URL textbox.

from pyjab.jabdriver import JABDriver
from pyjab.common.by import By

jabdriver = JABDriver("Rest Suite")
jabdriver.find_element(By.NAME, "apiURL").send_text("Completed!")

Do you have any ideas on why this code doesn’t work at all?

FYI, I opened the source code in Netbeans 15 and found the name of textbox “apiURL”.
But Eclipse IDE doesn’t show Name field in Property window. Is it normal?

Thank you!



This one line returns an error as below:

[Running] python -u "c:\Users\antho\projects\python\HelloWord.py"
2022-11-09 23:35:25,943 INFO pyjab init jab
2022-11-09 23:35:26,028 INFO pyjab init jab success
Traceback (most recent call last):
  File "c:\Users\antho\projects\python\HelloWord.py", line 10, in <module>
    jabdriver.find_element(By.NAME, "URL").send_text("Completed!")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 390, in find_element
    return dict_find[by](value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 296, in find_element_by_name
    return self.root_element.find_element_by_name(value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 965, in find_element_by_name
    return self.find_element(by=By.NAME, value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 1328, in find_element
    raise JABException(
pyjab.common.exceptions.JABException: ("jab element not found by 'name' with locator 'URL'", None)

[Done] exited with code=1 in 1.184 seconds

**Comment by anthony-nyc** [comment]
Hi Gary,

I have no ideas about this but I’ve finally noticed that Eclipse IDE has a few properties only for UI element and IDE provides a button named “Show Advanced Properties”.
However, Netbeans IDE 15 has much more properties for UI element, for example, jTextField2 has “Accessible Name” field as shown below.
It was blank and I entered jTextField2. After this, pyjab codes work as expected.

Here is my question. If Java developer didn’t specify Accessible Name for each UI element and GUI application is created without any Accessible Name, we are not able to use pyjab driver because we can’t identify UI elements.

Am I understanding correctly?

Would you please advise on this?

Thank you so much for your time.

Anthony


***@***.***




From: Anthony ***@***.***>
Sent: Wednesday, November 9, 2022 11:37 PM
To: ***@***.***>
Subject: RE: [gaozhao1989/pyjab] ERROR: Cannot install pyjab==1.0.0, pyjab==1.0.1, pyjab==1.0.3, pyjab==1.0.4, pyjab==1.0.5, pyjab==1.0.6, pyjab==1.0.7, pyjab==1.0.8, pyjab==1.0.9, pyjab==1.1.0, pyjab==1.1.1, pyjab==1.1.2, pyjab==1.1.3, pyjab==1.1.4, pyjab==1.1...

Hi Gary,

Thanks for your response.
While I was trying to figure out why pyjab is not able to access UI element using Name, I noticed that Access Bridge Explorer shows blank in Name field.

Could you please let me know how we can identify the name of UI elements?
I thought that we have to use Access Bridge Explorer but it shows blank in a field of Name.

For example, here<https://github.com/supanadit/restsuite/releases> is a sample Java GUI application and I wrote one line code below to access URL textbox.

from pyjab.jabdriver import JABDriver
from pyjab.common.by import By

jabdriver = JABDriver("Rest Suite")
jabdriver.find_element(By.NAME, "apiURL").send_text("Completed!")

Do you have any ideas on why this code doesn’t work at all?

FYI, I opened the source code in Netbeans 15 and found the name of textbox “apiURL”.
But Eclipse IDE doesn’t show Name field in Property window. Is it normal?

Thank you!



This one line returns an error as below:

[Running] python -u "c:\Users\antho\projects\python\HelloWord.py"
2022-11-09 23:35:25,943 INFO pyjab init jab
2022-11-09 23:35:26,028 INFO pyjab init jab success
Traceback (most recent call last):
  File "c:\Users\antho\projects\python\HelloWord.py", line 10, in <module>
    jabdriver.find_element(By.NAME, "URL").send_text("Completed!")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 390, in find_element
    return dict_find[by](value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabdriver.py", line 296, in find_element_by_name
    return self.root_element.find_element_by_name(value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 965, in find_element_by_name
    return self.find_element(by=By.NAME, value=value, visible=visible)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\pyjab\jabelement.py", line 1328, in find_element
    raise JABException(
pyjab.common.exceptions.JABException: ("jab element not found by 'name' with locator 'URL'", None)

[Done] exited with code=1 in 1.184 seconds

**Comment by gaozhao1989** [comment]
Hi Anthony,

`
Here is my question. If Java developer didn’t specify Accessible Name for each UI element and GUI application is created without any Accessible Name, we are not able to use pyjab driver because we can’t identify UI elements.
`
There are multiple method for find JABElement (Accessible Context of Java Component) in Pyjab.
For current version provide find by name, description, role, states, object depth, children count, index in parent and xpath(customized function, different within selenium).
Pyjab also available to find JABElement through another ways if developer not specific Accessible Name of Java Component.

**Comment by anthony-nyc** [comment]
Hi Gary,

Yes I see there is another way when Accessible Name is not specified by Developers.
For example, find_element_by_index_in_parent, can access UI element without Accessible Name.
But this doesn’t seem to support all type of UI elements.

Having said that, I realized that I need to automate Java GUI projects in Linux, not Windows.
I know your Git says pyjab works only for Windows.

Do you have any ideas on how we can do the same thing in Linux?
Any comments would be greatly appreciated.

Thank you so much!


from pyjab.jabdriver import JABDriver
jabdriver = JABDriver("Welcome!")
txt = jabdriver.find_element_by_index_in_parent(1)
txt.send_text("Done!")

**Comment by gaozhao1989** [comment]
Hi Anthony,

Can you give more details about function `find_element_by_index_in_parent` which not support in your scenarios.
Also, pyjab does not support other os(only on windows) because the JAB API does NOT support, you can reference with Oracle official description with this URL: https://www.oracle.com/java/technologies/javase/javase-tech-access-bridge.html
