### ISSUE TITLE
请问在canvas中绘制的界面内的元素能否获取到

### ISSUE THREAD

**Issue by shuiqukeyou** [gaozhao1989/pyjab#73]
感谢大佬开发了这个项目。

当我用AccessBridgeExplorer展开目标程序的节点时，到canvas这一级就无法继续展开了，显示没有更下级的child节点，但目标软件的主要功能全都集中在这个canvas中。

我JAVA写的很少，这是不是意味着这个软件的主要界面全是在canvas手搓出来的（但这个canvas的UI风格看上去非常JAVA），并不遵循swing或者awt的标准规则，导致JAB无法访问到其中的元素，我尝试按名称搜索了一些element，canvas外的element基本都能搜到，但canvas内的全都找不到。

请问是我获取元素的方法有问题，从而导致无法获取。还是JAB本身的限制导致其一开始就无法获取canvas内的元素，从而使得pyjab也无法获取元素。如果是后者的话是否有什么办法解决？

**Comment by gaozhao1989** [comment]
Hi,
Thanks for you mentioned on this. Unfortunately, canvas same as color picker, not support direct control by JAB.

**Comment by shuiqukeyou** [comment]
好的，非常感谢，和我想象的一样
